$board->AddRoom("TOPLT"); $board->AddRoom("DNLT");
$board->AddRoom("CENTER");
$board->AddRoom("TOPRT"); $board->AddRoom("DNRT");
$board->AddColorToRoom("TOPLT","R");
$board->AddColorToRoom("DNLT","G");
$board->AddColorsToRoom("CENTER","G","B","O");
$board->AddColorsToRoom("TOPRT","G","R","V","B");
$board->AddColorsToRoom("DNRT","R","R","O");
$board->AddPlayer("TOPLT");
$board->AddPlayer("TOPRT");
$board->AddPlayer("TOPRT");
$board->AddTargetToRoom("DNLT");
$board->AddTargetToRoom("DNRT");
$board->AddTargetToRoom("DNRT");
$board->AddDoor("TOPLT","DNLT","G","B");
$board->AddDoor("TOPLT","DNLT","R","R");
$board->AddDoor("TOPRT","DNRT","B","G");
$board->AddDoor("CENTER","TOPRT","G","O");
$board->AddDoor("CENTER","TOPRT","R","V");
$board->AddDoor("CENTER","DNRT","R","O");
$board->AddDoor("CENTER","DNRT","R","V");
