@proglist=(
	      "Newbie",
	      "Normal:Andariel",
	      "Normal:Duriel",
	      "Normal:Mephisto",
	      "Normal:Diablo",
	      "Slayer",
	      "Nightmare:Andariel",
	      "Nightmare:Duriel",
	      "Nightmare:Mephisto",
	      "Nightmare:Diablo",
	      "Champion",
	      "Hell:Andariel",
	      "Hell:Duriel",
	      "Hell:Mephisto",
	      "Hell:Diablo",
	      "Patriarch"
	      );

@classes=(
	     "Amazon",
	     "Sorceress",
	     "Necromancer",
	     "Paladin",
	     "Barbarian",
	     "Druid",
	     "Assassin"
	     );

@mercclasses=
    (
     "Rogue Scout,Fire Arrow,Normal",
     "Rogue Scout,Cold Arrow,Normal",
     "Rogue Scout,Fire Arrow,Nightmare",
     "Rogue Scout,Cold Arrow,Nightmare",
     "Rogue Scout,Fire Arrow,Hell",
     "Rogue Scout,Cold Arrow,Hell",
     "Desert Mercenary,Combat,Normal",
     "Desert Mercenary,Defensive,Normal",
     "Desert Mercenary,Offensive,Normal",
     "Desert Mercenary,Combat,Nightmare",
     "Desert Mercenary,Defensive,Nightmare",
     "Desert Mercenary,Offensive,Nightmare",
     "Desert Mercenary,Combat,Hell",
     "Desert Mercenary,Defensive,Hell",
     "Desert Mercenary,Offensive,Hell",
     "Eastern Sorceror,Fire Spells,Normal",
     "Eastern Sorceror,Cold Spells,Normal",
     "Eastern Sorceror,Lightning Spells,Normal",
     "Eastern Sorceror,Fire Spells,Nightmare",
     "Eastern Sorceror,Cold Spells,Nightmare",
     "Eastern Sorceror,Lightning Spells,Nightmare",
     "Eastern Sorceror,Fire Spells,Hell",
     "Eastern Sorceror,Cold Spells,Hell",
     "Eastern Sorceror,Lightning Spells,Hell",
     "Barbarian,Normal",
     "Barbarian,Normal",
     "Barbarian,Nightmare",
     "Barbarian,Nightmare",
     "Barbarian,Hell",
     "Barbarian,Hell"
     );


@RogueScoutNames=
    (
     "Aliza",
     "Amplisa",
     "Annor",
     "Abhaya",
     "Elly",
     "Paige",
     "Basanti",
     "Blaise",
     "Kyoko",
     "Klaudia",
     "Kundri",
     "Kyle",
     "Visala",
     "Elexa",
     "Floria",
     "Fiona",
     "Gwinni",
     "Gaile",
     "Hannah",
     "Heather",
     "Iantha",
     "Diane",
     "Isolde",
     "Divo",
     "Ithera",
     "Itonya",
     "Liene",
     "Maeko",
     "Mahala",
     "Liaza",
     "Meghan",
     "Olena",
     "Oriana",
     "Ryann",
     "Rozene",
     "Raissa",
     "Sharyn",
     "Shikha",
     "Debi",
     "Tylena",
     "Wendy"
     );

@DesertMercenaryNames=
    (
     "Hazade",
     "Alhizeer",
     "Azrael",
     "Ahsab",
     "Chalan",
     "Haseen",
     "Razan",
     "Emilio",
     "Pratham",
     "Fazel",
     "Jemali",
     "Kasim",
     "Gulzar",
     "Mizan",
     "Leharas",
     "Durga",
     "Neeraj",
     "Ilzan",
     "Zanarhi",
     "Waheed",
     "Vikhyat"
     );

@EasternSorcerorNames=
    (
     "Jelani",
     "Barani",
     "Jabari",
     "Devak",
     "Raldin",
     "Telash",
     "Ajheed",
     "Narphet",
     "Khaleel",
     "Phaet",
     "Geshef",
     "Vanji",
     "Haphet",
     "Thadar",
     "Yatiraj",
     "Rhadge",
     "Yashied",
     "Jarulf",
     "Flux",
     "Scorch"
     );

@BarbarianNames=
    (
     "Varaya",
     "Khan",
     "Klisk",
     "Bors",
     "Brom",
     "Wiglaf",
     "Hrothgar",
     "Scyld",
     "Healfdane",
     "Heorogar",
     "Halgaunt",
     "Hygelac",
     "Egtheow",
     "Bohdan",
     "Wulfgar",
     "Hild",
     "Heatholaf",
     "Weder",
     "Vikhyat",
     "Unferth",
     "Sigemund",
     "Heremod",
     "Hengest",
     "Folcwald",
     "Frisian",
     "Hnaef",
     "Guthlaf",
     "Oslaf",
     "Yrmenlaf",
     "Garmund",
     "Freawaru",
     "Eadgils",
     "Onela",
     "Damien",
     "Erfor",
     "Weohstan",
     "Wulf",
     "Bulwye",
     "Lief",
     "Magnus",
     "Klatu",
     "Drus",
     "Hoku",
     "Kord",
     "Uther",
     "Ip",
     "Ulf",
     "Tharr",
     "Kaelim",
     "Ulric",
     "Alaric",
     "Ethelred",
     "Caden",
     "Elgifu",
     "Tostig",
     "Alcuin",
     "Emund",
     "Sigurd",
     "Gorm",
     "Hollis",
     "Ragnar",
     "Torkel",
     "Wulfstan",
     "Alban",
     "Barloc",
     "Bill",
     "Theodoric"
     );




1;
